format = "$username$hostname$directory$nodejs$python$nix_shell$git_branch$git_state$git_status$cmd_duration$aws$line_break$character"
palette = "catppuccin_mocha"

[aws]
disabled = false
detect_folders = ["node_modules"]
detect_files = ["node_modules"]
format = '[$symbol ($profile)]($style)'
symbol = '☁️'
style = 'yellow'

[aws.profile_aliases]
dev-nico-admin = 'nico-dev'
dev-uk = 'dev'
prod-uk = 'prod'

[character]
error_symbol = "[λ](bright-red)"
success_symbol = "[λ](bright-pink)"
# success_symbol = "[λ▲](bright-pink)"
vicmd_symbol = "[λ](green)"

[cmd_duration]
format = " [$duration]($style) "
style = "yellow"

[directory]
style = "#d5a8e3"
truncate_to_repo = false
truncation_length = 2

[git_branch]
format = "[$branch]($style)"
style = "#4C566A"

[git_state]
format = "([ $state ($progress_current/$progress_total) ] ($style)) "
style = "black"

[git_status]
conflicted = "​"
deleted = "​"
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind)]($style)"
modified = "​"
renamed = "​"
staged = "​"
stashed = "≡"
style = "cyan"
untracked = "​"

[nix_shell]
format = "❄️ "

[nodejs]
format = "[$symbol($version)]($style) "
style = "#88C0D0"
version_format = "${raw}"

[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[terraform]
disabled = true
